apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: foo
  namespace: buffer-demo
spec:
  selector:
    matchLabels: {model: foo}        # matches primary AND buffer pods
  targetPorts:
    - number: 8000
  endpointPickerRef:
    name: foo-epp
